server:
  port: 8080

spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://39.108.236.16:3306/car?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 248248
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.carrental.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      carrental:
        dao: debug